import 'dart:convert';

import 'package:firebase_ai/firebase_ai.dart';
import 'package:flutter/foundation.dart';

import '../models/recipe_model.dart';
import '../../../fridge/domain/entities/fridge_item.dart';
import '../../../stock/domain/entities/stock_item.dart';

/// Data source for AI-powered recipe recommendations using Firebase AI.
///
/// This class uses Google's Gemini AI model to generate recipe recommendations
/// based on available inventory. It constructs prompts with current fridge
/// and stock items, then parses AI responses to extract recipe information.
class RecipeAIDataSource {
  /// Generates recipe recommendations using AI based on current inventory.
  ///
  /// Sends a prompt to Gemini AI with the list of available ingredients
  /// from both fridge and stock, requesting recipe suggestions in Japanese.
  /// The AI is instructed to assume basic seasonings are available.
  ///
  /// Parameters:
  ///   [fridgeItems] - List of items in the fridge
  ///   [stockItems] - List of items in stock
  ///   [count] - Number of recipes to generate
  ///
  /// Returns a list of [RecipeModel] objects generated by AI.
  /// Returns an empty list if AI generation fails or returns invalid data.
  Future<List<RecipeModel>> getRecipeRecommendations({
    required List<FridgeItem> fridgeItems,
    required List<StockItem> stockItems,
    required int count,
  }) async {
    try {
      // Firebase AI 초기화 (Gemini 2.0 Flash 사용)
      final model = FirebaseAI.googleAI().generativeModel(
        model: 'gemini-2.0-flash',
      );

      // 재고 목록을 문자열로 변환
      final inventoryText = _buildInventoryText(
        fridgeItems: fridgeItems,
        stockItems: stockItems,
      );

      // 프롬프트 생성
      final promptText =
          '''
以下の冷蔵庫とストックの在庫を使って、$count個のレシピを提案してください。

在庫リスト:
$inventoryText

【重要】基本調味料について:
以下の基本調味料は常に持っているものとして扱ってください。在庫リストに含まれていなくても、レシピに使用して構いません:
- 塩、砂糖、こしょう、醤油、みりん、酒、酢、油、バター、オリーブオイル、にんにく、生姜（基本的な調味料全般）

レシピ作成の注意事項:
1. 在庫リストにある材料を優先的に使用してください
2. 基本調味料は在庫リストに含まれていなくても使用可能です
3. 在庫リストにない特別な材料はできるだけ避けてください
4. 実用的で作りやすいレシピを提案してください

各レシピについて、以下の形式でJSON配列として返してください:
[
  {
    "title": "レシピ名",
    "description": "レシピの簡単な説明",
    "ingredients": ["材料1", "材料2", ...],
    "instructions": ["手順1", "手順2", ...],
    "cookingTime": 30,
    "servings": 2
  },
  ...
]

JSONのみを返してください。説明や追加のテキストは不要です。
''';

      final prompt = [Content.text(promptText)];
      final response = await model.generateContent(prompt);
      final text = response.text?.trim() ?? '';

      if (text.isEmpty) {
        debugPrint('AI response is empty.');
        return [];
      }

      // Parse JSON response
      final recipes = _parseRecipesFromJson(text);
      debugPrint('Recipe recommendations successful: ${recipes.length} recipes');
      return recipes;
    } catch (e) {
      debugPrint('Recipe recommendation failed: $e');
      return [];
    }
  }

  /// 재고 목록을 텍스트로 변환합니다.
  String _buildInventoryText({
    required List<FridgeItem> fridgeItems,
    required List<StockItem> stockItems,
  }) {
    final buffer = StringBuffer();

    if (fridgeItems.isNotEmpty) {
      buffer.writeln('冷蔵庫:');
      for (final item in fridgeItems) {
        buffer.writeln(
          '  - ${item.name} (数量: ${item.quantity}${item.category != null ? ', カテゴリ: ${item.category}' : ''})',
        );
      }
    }

    if (stockItems.isNotEmpty) {
      if (fridgeItems.isNotEmpty) {
        buffer.writeln();
      }
      buffer.writeln('ストック:');
      for (final item in stockItems) {
        buffer.writeln(
          '  - ${item.name} (数量: ${item.quantity}${item.category != null ? ', カテゴリ: ${item.category}' : ''})',
        );
      }
    }

    return buffer.toString();
  }

  /// Parses AI JSON response into a list of recipe models.
  ///
  /// Handles various JSON formats that the AI might return, including
  /// responses wrapped in markdown code blocks. Validates that the
  /// response is a proper JSON array and converts each item to a
  /// [RecipeModel].
  ///
  /// Parameters:
  ///   [jsonText] - The raw JSON text from the AI response
  ///
  /// Returns a list of [RecipeModel] objects, or an empty list if parsing fails.
  List<RecipeModel> _parseRecipesFromJson(String jsonText) {
    try {
      // JSON 배열 부분만 추출 (```json 또는 ``` 제거)
      var cleanedText = jsonText.trim();

      // 마크다운 코드 블록 제거
      if (cleanedText.contains('```')) {
        final startIndex = cleanedText.indexOf('[');
        final endIndex = cleanedText.lastIndexOf(']');
        if (startIndex != -1 && endIndex != -1 && endIndex > startIndex) {
          cleanedText = cleanedText.substring(startIndex, endIndex + 1);
        } else {
          // ```json ... ``` 형식 처리
          final lines = cleanedText.split('\n');
          cleanedText = lines
              .skipWhile((line) => line.trim().startsWith('```'))
              .takeWhile((line) => !line.trim().startsWith('```'))
              .join('\n')
              .trim();
        }
      }

      // JSON 파싱
      final decoded = jsonDecode(cleanedText);

      // Verify it's an array
      if (decoded is! List) {
        debugPrint('JSON is not in array format: $decoded');
        return [];
      }

      final json = decoded;
      return json
          .map((item) {
            if (item is! Map<String, dynamic>) {
              debugPrint('Recipe item is not in Map format: $item');
              return null;
            }

            return RecipeModel.fromJson(item);
          })
          .whereType<RecipeModel>()
          .toList();
    } catch (e) {
      debugPrint('JSON parsing failed: $e');
      debugPrint('Original text: $jsonText');
      return [];
    }
  }
}
