// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsNgJsLyFoYErJgX_LAhM8bIThKAvYrkM',
    appId: '1:630905075034:web:3fbb545be47d6d989a6f63',
    messagingSenderId: '630905075034',
    projectId: 'pantry-ae10e',
    authDomain: 'pantry-ae10e.firebaseapp.com',
    storageBucket: 'pantry-ae10e.firebasestorage.app',
    measurementId: 'G-PPFY5WXHC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLoTTDjAKUNceFeJGW_dnsRYVBtW_KTbg',
    appId: '1:630905075034:android:a2cc5bbf1d05052e9a6f63',
    messagingSenderId: '630905075034',
    projectId: 'pantry-ae10e',
    storageBucket: 'pantry-ae10e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVzb34GUq9Bmw9U05MOcwwt6bas8hiVRY',
    appId: '1:630905075034:ios:a8722ec81131b20e9a6f63',
    messagingSenderId: '630905075034',
    projectId: 'pantry-ae10e',
    storageBucket: 'pantry-ae10e.firebasestorage.app',
    iosBundleId: 'com.itz.pantry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVzb34GUq9Bmw9U05MOcwwt6bas8hiVRY',
    appId: '1:630905075034:ios:a8722ec81131b20e9a6f63',
    messagingSenderId: '630905075034',
    projectId: 'pantry-ae10e',
    storageBucket: 'pantry-ae10e.firebasestorage.app',
    iosBundleId: 'com.itz.pantry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsNgJsLyFoYErJgX_LAhM8bIThKAvYrkM',
    appId: '1:630905075034:web:13edb499ae6c16b69a6f63',
    messagingSenderId: '630905075034',
    projectId: 'pantry-ae10e',
    authDomain: 'pantry-ae10e.firebaseapp.com',
    storageBucket: 'pantry-ae10e.firebasestorage.app',
    measurementId: 'G-0FYW6VB1ZK',
  );
}
